apiVersion: v1
kind: Service
metadata:
  name: javadocky
  labels:
    app: javadocky
spec:
  selector:
    app: javadocky
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: "34.96.133.137"
